import atom from './popOut_Symbols/atom.svg'
import dialog from './popOut_Symbols/dialog.svg'
import prad from './popOut_Symbols/prad.svg'
import maski from './popOut_Symbols/maski.svg'
import banknot from './popOut_Symbols/banknot.svg'

export const text = [
    {
        itemId: "arrow_lab",
        title: "Research and scholarships",
        text: "Social and economic development in Europe depends on research and innovation. Increasing and strengthening research investments are priorities in all European countries. Europe 2020 has a goal of increasing research and development (R&D) investments to 3% of GDP. Individual EU Member States and EEA EFTA countries have set specific national targets. European and international cooperation in research and innovation is a priority shared by all European countries. Transnational European research cooperation is promoted through the EU Framework Programme for research and innovation, Horizon 2020. However, limited economic resources and the instability of research funding pose special challenges to beneficiary countries, both in meeting their R&D policy goals and in fully participating in international cooperation. The European Research Area (ERA) promotes transnational European research cooperation and is part of the Europe 2020 Innovation Union Flagship Initiative, a key instrument in achieving the goals set out in the Europe 2020 strategy for jobs and growth.",
        symbol1: (<img src={atom} alt="error"/>),    
    },
    {
        itemId: "arrow_fan",
        title: "Environmental protection and green technology",
        text: "The European energy sector is currently facing the challenge of moving from the use of fossil fuels and high energy consumption to an increased use of renewable energy and high energy efficiency. This move is fundamental for reducing greenhouse gas emissions. Otherwise, Europe will not be able to meet its commitments to reduce emissions. Iceland, Liechtenstein and Norway are committed to international efforts to tackle climate change, a commitment shared with the European Union. The EEA and Norway Grants will fund programmes focusing on renewable energy, energy security and energy efficiency in line with the Energy Union objectives and the Europe 2020 strategy targets of 20% reduction of greenhouse gas emission, 20% of energy from renewables and 20% increase in energy efficiency. Well-functioning and efficient energy markets – with adequate infrastructure and an effective legislative framework – are preconditions for security of supply, and for developing an effective climate policy in Europe. This calls for a climate change-focused energy model. Such a model will not only address the need to mitigate climate change: a push towards less carbon intensive economies will also promote research and innovation in climate-friendly technology. It will create job opportunities in sectors where a highly skilled workforce is needed. Promoting the use of domestic renewable energy and less carbon intensive technologies is therefore a key element for a more competitive Europe.",
        symbol1: (<img src={prad} class="piorun" alt="error"/>),
    },
    {
        itemId: "arrow_flag",
        title: "Worthy Work and Tripartite Dialogue",
        text: "Norway and the EU support the principles of social dialogue – the dialogue between workers and employers – and social dialogue is a key element of the Nordic social model. This programme area supports strengthened dialogue and ensures that beneficiary countries are better placed to deal with the challenges of high unemployment and to establish decent work objectives, such as non-discrimination and receiving a living wage. The programme area supports the objectives of increased employment and the EU’s Social Europe Initiative under the framework of Europe 2020. The programme area also builds on the International Labour Organisation’s (ILO) Decent Work Agenda. Decent work covers social dialogue, strengthened rights of employees, employment and social protection. The ILO encourages tripartite cooperation to promote harmonious labour relations. Tripartite cooperation brings employers, employees and government together to collaborate, consult, discuss and resolve common concerns related to employment. A tripartite approach has the advantage of informing people and thereby enable them to help design and implement national policies that will achieve fair terms and working conditions that are favourable for all.",
        symbol1: (<img src={dialog} alt="error"/>), 
    },
    {
        itemId: "arrow_people",
        title: "Social and regional development",
        text: "According to the EU, people are at risk of living in poverty if their income falls below 60% of median income in the country where they live. In 2011, more than 119 million people – 24% of the EU population – were at risk of poverty. The Europe 2020 strategy aims to reduce this number by 20 million by 2020. Special attention is paid to measures aimed at those running the highest risk of poverty and social exclusion: the unemployed and low-skilled, non-EU migrants and single parent families. There is an urgent need to address youth unemployment (23% in EU countries in 2013) and the unemployment of cultural and ethnic minorities and non-EU migrants. The EEA and Norway Grants target the challenges that the most vulnerable regions in the beneficiary countries are currently facing. The Grants do this by providing support to help address poverty at the root causes: lack of job prospects, lack of job capacity and problems leading to social exclusion. The support aims to empower communities to develop innovative, inclusive and bottom-up approaches to involve people in the development of their community and create better prospects for the disadvantaged. It also aims to stimulate knowledge exchange between municipalities through networking and policy exchanges. The Europe 2020 strategy and the EU’s cohesion policy take account of the crucial role Europe’s cities and regions play for future smart, sustainable and inclusive growth. Addressing poverty is a key priority in this strategy.",
        symbol1: (<img src={banknot} alt="error"/>),
    },
    {
        itemId: "arrow_cinema",
        title: "Cultural heritage",
        text: "Culture’s intrinsic value is widely recognised. Beyond this value the cultural and creative sectors are important drivers of economic growth, job development and social inclusion. In its impact assessment for the EU Creative Europe programme, the European Commission underlines the transformative economic and social power of culture: the cultural and creative sectors account for approximately 4.5% of the Union's GDP (2008) and employ some 3.8% of its workforce. These sectors trigger spill-overs in other economic areas such as tourism. They fuel the development of innovative content for ICT and greatly contribute to education, social inclusion and social innovation. The EEA and Norway Grants stimulate the safeguarding of cultural heritage, cultural entrepreneurship and cultural cooperation because of the sector’s role in local and regional development, capacity development and social inclusion. The Grants recognise the sector’s potential as a driver of economic and social innovation in and outside of the cultural and creative sectors. They acknowledge that the cultural and creative sectors also play a role in stimulating social inclusion and combatting discrimination; they help forge solidarity between people and strengthen democracy. Across Europe there is a growing concern related to radicalism and violent extremism. Culture plays a role in counterbalancing this due to its role in stimulating greater mutual understanding.",
        symbol1: (<img src={maski} alt="error"/>),
    },
]